[project]
name = "dealr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dynamixel-controller>=0.9.2",
    "dynamixel-sdk>=3.7.31",
]
